# Generated by Django 5.1.2 on 2024-12-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_category_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
    ]
